# apiVersion: extensions/v1beta1
# kind: Deployment
# metadata:
#   name: nginx
#   labels:
#     name: nginx
# spec:
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         name: nginx
#     spec:
#       containers:
#         - name: nginx
#           # Nginx 1.16 is current stable relase (as of 07/03/20)
#           # Alpine OS allows performance, memory and security boost (in most cases)
#           image: nginx:1.16-alpine
